### ISSUE TITLE
US ID1: As a user, I want to register for the app to play a game with other registered users. 

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#2]
- [x] sopra-fs23-group-12/4Bubbles_Client#5
- [x] sopra-fs23-group-12/4Bubbles_Client#4
- [x] sopra-fs23-group-12/4Bubbles_Client#3
- [x] sopra-fs23-group-12/4Bubbles_Client#2

**Comment by dariokueffer** [comment]
@a1ps chömmer schliesse, oder? Optional lömmer weg, alels anderi funktioniert guet.
