### ISSUE TITLE
US ID2: As a player I want to have a central page to start / join new games, access my friend list and view my profile stats to be able to play the game, connect with others, or track my data

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#3]
- [x] sopra-fs23-group-12/4Bubbles_Client#10
- [x] sopra-fs23-group-12/4Bubbles_Client#58
- [x] sopra-fs23-group-12/4Bubbles_Client#8
- [x] sopra-fs23-group-12/4Bubbles_Client#57
- [x] sopra-fs23-group-12/4Bubbles_Client#6
- [x] sopra-fs23-group-12/4Bubbles_Client#48
