### ISSUE TITLE
US ID9: As a user I want to be able to see after each question if my answer was wrong or right and how many points I and the other players scored.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#8]
- [x] sopra-fs23-group-12/4Bubbles_Client#48
- [x] sopra-fs23-group-12/4Bubbles_Client#47

- [x] - [x] sopra-fs23-group-12/4Bubbles_Client#22

- [x] I can see in that resolution window as well through either some text or color coding if my answer was right or false.

- [x] After a few seconds the pop-up window will disappear automatically, the next question will be visible then.

- [x] My awarded points will be automatically added to the constant display of the current ranking and the ranking will be adapted, such that the highest score will still be on the top.
- [x] sopra-fs23-group-12/4Bubbles_Server#50
- [x] sopra-fs23-group-12/4Bubbles_Server#51

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
backend: 
when the time for answering is up, the evaluation and the corret answer are sent to each player

**Comment by dariokueffer** [comment]
@a1ps chömmer schliesse, ok?
